name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build with Gradle
      run: ./gradlew bootJar

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      run: echo "Karthik@142" | docker login --username "karthik142" --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag karthik142/elibrary:elibrary

    - name:  Docker run image
      run: docker run -d --name con1 -p 8080:8080 karthik142/elibrary:elibrary

    - name: Push Docker image to Docker Hub
      run: docker push karthik142/elibrary:elibrary
